filter:
  excluded_paths: [tests/*]
tools:
  external_code_coverage:
    timeout: 600
    runs: 2
build:
  environment:
    php:
      version: 7.1
  dependencies:
    before:
      - composer require phpunit/phpunit:^7.0 --dev
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          -   command: vendor/bin/phpunit --coverage-clover=clover.xml
              coverage:
                file: clover.xml
                format: php-clover
